### PR TITLE
Update header search paths for React v0.19.0

### PR DESCRIPTION
**Pull request by rjbaker**

### CODE REVIEW

**Comment by rahuljiresal** [comment]
@rjbaker I see that you've added `$(SRCROOT)/../../React` and `recursive` to the header search paths, but in an ideal scenario (such as the repo's folder structure), there will be no React folder two levels up from the source root directory. Was this fix specific to your project?

**Comment by rjbaker** [comment]
Hi @rahuljiresal nothing specific about my project. The paths are different in React 0.19. My project is based on the boilerplate created after running `react-native init myProject`.

react-native-auto-updater was installed following the guide in the readme.

SRCROOT resolves to `/path/to/myprojectdir/node_modules/react-native-auto-updater/ios/`

Full search path is: `/path/to/myprojectdir/node_modules/react-native-auto-updater/ios/../../react-native/React` which is correct.

```
react-native-cli: 0.1.10
npm -v
2.14.12
node -v
v4.2.4
```

screen shot 2016-02-09 at 08 25 12

**Comment by rahuljiresal** [comment]
I encountered the same thing in a new project yesterday and this fixed it. React's iOS paths have changed in the later versions. I'm merging this pull request. Thanks a lot! Really appreciate the help.

**Comment by rjbaker** [comment]
No worries. Thanks! :+1:

**Pull request merged**
